### PR TITLE
Handle deprecated requestPermission APi in Safari 12+

### LINKED ISSUE #117: Safari requestPermission() Promise not supported.
Hello,

According to the MDN, Safari does not support the `requestPermission().then()` Promise version.

Reference: https://developer.mozilla.org/en-US/docs/Web/API/Notification/requestPermission#Browser_compatibility

So when `Push.Permission.request()` is called in Safari users get the following error:

```
undefined is not an object (evaluating 'this._win.Notification.requestPermission().then')
```

Due to this block: https://github.com/Nickersoft/push.js/blob/master/src/classes/Permission.js#L34-L39

Cheers,
Andrew

### PR DESCRIPTION
**Pull request by andjosh**
The assumption was that Safari would not remove the webkit prefix
without also conforming to the promise-based requestPermission API. They
dropped the prefix and did not update to Promises. This checks the
return value of the requestPermission call and treats it as a Promise
when possible. Otherwise, it always passes the callback version for the
old API.

Ref: https://developer.mozilla.org/en-US/docs/Web/API/Notification/requestPermission

Ref: https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/LocalNotifications/LocalNotifications.html#//apple_ref/doc/uid/TP40012932-SW1

Fixes #117 and #124, tested in modern Safari, Chrome, FF, IE. 

Re-open of #190 with fewer edits.

### CODE REVIEW

**Comment by theLufenk** [comment]
@andjosh Please go through the review comments for some clarifications.

@Nickersoft Would like your take on this too.

 Overall LGTM.

File: src/push/Permission.js [hunk 1]
```diff
@@ -62,13 +66,14 @@ export default class Permission {
...
         ) {
-            /* Chrome 23+ */
-            this._win.Notification
-                .requestPermission()
-                .then(resolve)
-                .catch(function() {
+            /* Safari 12+ */
+            request = this._win.Notification.requestPermission(resolve);
+            if (request && request.then) {
+                /* Chrome 23+ */
```
Comment (Nickersoft) [inline src/push/Permission.js]: I would fix the indentation here to match the original comment

File: src/push/Permission.js [hunk 2]
```diff
@@ -62,13 +66,14 @@ export default class Permission {
             this._win.Notification &&
             this._win.Notification.requestPermission
         ) {
-            /* Chrome 23+ */
-            this._win.Notification
-                .requestPermission()
-                .then(resolve)
-                .catch(function() {
+            /* Safari 12+ */
```
Comment (Nickersoft) [inline src/push/Permission.js]: I would move the "Chrome 23+" comment and add it to this comment to show this block covers both Safari 12+ and Chrome 23+

File: src/push/Permission.js [hunk 3]
```diff
@@ -62,13 +66,14 @@ export default class Permission {
...
+            request = this._win.Notification.requestPermission(resolve);
+            if (request && request.then) {
```
Comment (Nickersoft) [inline src/push/Permission.js]: I'm a little confused here.. this will prevent the console from erroring, but what is the fallback if the request variable proves to not be a promise? Does it just do nothing?

File: src/push/Permission.js [hunk 4]
```diff
@@ -41,13 +41,17 @@ export default class Permission {
...
         var resolve = (result = this._win.Notification.permission) => {
+            if (resolved) return;
+            resolved = true;
             if (typeof result === 'undefined' && this._win.webkitNotifications)
                 result = this._win.webkitNotifications.checkPermission();
             if (result === this.GRANTED || result === 0) {
                 if (onGranted) onGranted();
             } else if (onDenied) onDenied();
         };
+        var request;
```
Comment (Nickersoft) [inline src/push/Permission.js]: I would moved this declaration to where `request` is actually defined. I believe the convention is you only define uninitialized variables in the top-most code block, and because this is used in a conditional block, its declaration should also be in that block.

File: src/push/Permission.js [hunk 5]
```diff
@@ -41,13 +41,17 @@ export default class Permission {
     _requestWithCallback(onGranted: () => void, onDenied: () => void) {
```
Comment (Nickersoft) [inline src/push/Permission.js]: **All of my comments here also apply to the _requestAsPromise() method as well, as the code is structured in the exact same way between methods**

**Comment by Nickersoft** [comment]
@andjosh @theLufenk Had a few questions / comments. Overall looks good :)

File: src/push/Permission.js (hunk 2 above)
Comment (andjosh) [reply src/push/Permission.js]: I don't think I understand. The line below (line 70) handles Safari 12's case and then (pun intended!) lines 71-75 handle Chrome 23+.

File: src/push/Permission.js (hunk 3 above)
Comment (andjosh) [reply src/push/Permission.js]: If the request variable is not a promise, we are in Safari 12. In this version of Safari, the result of `requestPermission` is `undefined`. In Chrome 23+, the result of `requestPermission` is a Promise.

Comment (andjosh) [reply src/push/Permission.js]: See reference links in pull request body.

Comment (Nickersoft) [reply src/push/Permission.js]: Ah, I see.. alright that makes sense. I take it then in Chrome the passed `resolve` argument to `requestPermission()` is just ignored? Would you mind just adding some comments elaborating on the logic here just so it's easier to understand at first glance? More specifically, probably just mentioning how that argument will be used in Safari but not Chrome, if that makes sense.

File: src/push/Permission.js (hunk 2 above)
Comment (Nickersoft) [reply src/push/Permission.js]: I got it now. You can ignore this review then. See my other response for suggestions as to how these comments can be improved though.

**Comment by theLufenk** [comment]
_nudge_  @andjosh 
Please respond to my comments too. I would want to pull your changes ASAP as this addresses a high priority bug. Thanks.

**Comment by andjosh** [comment]
@theLufenk I don't see any comments from you here...

screenshot 2018-10-31 09 08 09

**Comment by theLufenk** [comment]
@andjosh My bad. Should be visible now ?

File: src/push/Permission.js [hunk 6]
```diff
@@ -41,13 +41,17 @@ export default class Permission {
...
         const existing = this.get();
 
+        var resolved = false;
```
[the remark this answers is not in the document]
Comment (andjosh) [reply src/push/Permission.js]: I added this (and reference it in the body of the `resolve` function to prevent doubly-executing the resolution callback. This will prevent a future issue if Safari (or Chrome) support both the callback and Promise style of `requestPermission` simultaneously.

File: src/push/Permission.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (andjosh) [reply src/push/Permission.js]: It possibly makes it redundant, but I just prefer not to assume (as Safari is already not conforming to one standard) that when Safari _does_ return something, it will be a Promise.

Comment (andjosh) [reply src/push/Permission.js]: Yes, in Chrome, the unused argument to `requestPermission()` is ignored.

I'll add comments! :)

File: src/push/Permission.js (hunk 6 above)
[the remark this answers is not in the document]
Comment (theLufenk) [reply src/push/Permission.js]: I highly doubt that would happen. But being future-proof can't hurt. I consider this resolved.

**Comment by theLufenk** [comment]
@andjosh Travis build seems to be failing. Could you please address it. 
I'll go ahead and merge right after.

**Comment by andjosh** [comment]
@theLufenk I am unclear on what is failing the Travis CI.

I believe it is due to a new version of Node combined with the babel/dependency updates pending in other pull requests.

Evidence:
See this issue: https://github.com/nodejs/node/issues/20325

[This build succeeded][0] on node v8.12.0 and now [the latest build fails][1] on node v10.13.0 with no changes in this pull request patch.

[0]: https://travis-ci.org/Nickersoft/push.js/builds/447992862
[1]: https://travis-ci.org/Nickersoft/push.js/builds/448916913

**Comment by andjosh** [comment]
I think we would rather not introduce dependency/package changes in the context of this pull request.

**Comment by andjosh** [comment]
_nudge_ :)

**Comment by andjosh** [comment]
*bump* :)

**Comment by Nickersoft** [comment]
Hey @andjosh! Got to apologize.. this ticket crossed my mind this morning and I found it odd that I hadn't heard anything about it and that @theLufenk hadn't reached out. Looks like it's the [Node 10 crash](https://github.com/gulpjs/gulp/issues/2162) rearing its ugly head again. I would [update the Travis config to use an explicit Node version](https://github.com/Nickersoft/push.js/blob/master/.travis.yml#L9) (I recommend 8.12 or 8.11.4). Looks like [10.x entered LTS status](https://github.com/nodejs/Release#release-schedule), so the build is using it now. The config was written at a time when 10.x was the new kid on the block and 8.x was forever the LTS, but I guess that has since changed. Info on updating the config can be [found here](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/).

**Comment by Nickersoft** [comment]
As tech debt, we should probably fix that Node 10 crash.. not sure what's causing it though.

**Comment by andjosh** [comment]
Node version specified in the Travis config. All passing now. :)

**Comment by theLufenk** [comment]
@andjosh Apologies for the delay. Went into an area with no network coverage and got kind of stuck there.

> As tech debt, we should probably fix that Node 10 crash.. not sure what's causing it though. May need to update `gulp` version @theLufenk.

@Nickersoft 
This indeed would entail a tech debt. I had spend a few days scratching my head on a viable fix for this but I'm afraid I could not. For now, we can go head with the merge using the workaround, and let's open an issue to make sure we address this soon.
